services:
  ollama:
    build:
      context: ollama
      dockerfile: Dockerfile
    container_name: ollama
    environment:
      OLLAMA_BASE_URL: ${SERVER_HOST:-127.0.0.1}
    hostname: ollama
    image: lag_rag/ollama:local
    restart: unless-stopped
    ports:
      - "${SERVER_HOST:-127.0.0.1}:11434:11434/tcp"
    networks:
      common: null
    volumes:
      - type: volume
        source: ollama_data
        target: /root/.ollama
        volume: {}

  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    hostname: app
    image: lag_rag/app:local
    restart: unless-stopped
    networks:
      common: null
    ports:
      - "8501:8501/tcp"
    depends_on:
      - ollama

  jupyter:
    build:
      context: jupyter
      dockerfile: Dockerfile
    container_name: jupyter
    environment:
      JUPYTER_TOKEN: token
    hostname: jupyter
    image: lag_rag/jupyter:local
    ports:
      - "${SERVER_HOST:-127.0.0.1}:8888:8888/tcp"
    networks:
      common: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./jupyter/src
        target: /home/jovyan/work
        bind:
          create_host_path: false

  openwebui:
    build:
      context: openwebui
      dockerfile: Dockerfile
    container_name: openwebui
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    hostname: openwebui
    image: lag_rag/openwebui:local
    restart: unless-stopped
    volumes:
      - type: volume
        source: openwebui_data
        target: /app/backend/data
        volume: {}
    networks:
      common: null
    ports:
      - "${SERVER_HOST:-127.0.0.1}:8080:8080/tcp"

volumes:
  ollama_data:
    driver: local
  openwebui_data:
    name: dockerverse_openwebui_data
    driver: local

networks:
  common:
    driver: bridge